<template>
  <div class="space-y-6">
    <!-- Filter and Generate Section -->
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-3">
        <select 
          v-model="filterType" 
          class="block px-4 py-2 border border-gray-300 rounded-lg leading-5 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        >
          <option value="">All Types</option>
          <option v-for="t in types" :key="t" :value="t">{{ t }}</option>
        </select>
        <input 
          type="date" 
          v-model="from" 
          class="block px-4 py-2 border border-gray-300 rounded-lg leading-5 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" 
        />
        <input 
          type="date" 
          v-model="to" 
          class="block px-4 py-2 border border-gray-300 rounded-lg leading-5 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" 
        />
      </div>

      <div>
        <button 
          @click="generateReport" 
          class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors duration-200 flex items-center gap-2"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
          </svg>
          Generate Report
        </button>
      </div>
    </div>

    <!-- Reports Table -->
    <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-for="r in filteredReports" :key="r.id" class="hover:bg-gray-50 transition-colors">
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ r.title }}</td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800">
                {{ r.type }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ r.date }}</td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ r.generatedBy }}</td>
            <td class="px-6 py-4 whitespace-nowrap">
              <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium" :class="getStatusClass(r.status)">
                {{ r.status }}
              </span>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
              <button 
                @click="downloadReport(r)" 
                class="text-green-600 hover:text-green-900 mr-4 transition-colors"
              >
                Download
              </button>
              <button 
                @click="viewReport(r)" 
                class="text-blue-600 hover:text-blue-900 transition-colors"
              >
                View
              </button>
            </td>
          </tr>
        </tbody>
      </table>
      
      <!-- Empty State -->
      <div v-if="filteredReports.length === 0" class="text-center py-12">
        <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No reports found</h3>
        <p class="mt-1 text-sm text-gray-500">Try adjusting your filters or generate a new report.</p>
      </div>
    </div>

    <!-- Report Viewer Modal -->
    <div v-if="viewing" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" @click="viewing = null">
      <div class="bg-white rounded-lg shadow-xl max-w-4xl w-full mx-4 max-h-[90vh] overflow-y-auto p-6" @click.stop>
        <div class="flex items-center justify-between mb-4">
          <h3 class="text-lg font-semibold text-gray-900">{{ viewing.title }}</h3>
          <button @click="viewing = null" class="text-gray-400 hover:text-gray-600">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>
        <div class="mb-4 text-sm text-gray-600">
          <span class="font-medium">Type:</span> {{ viewing.type }} | 
          <span class="font-medium">Date:</span> {{ viewing.date }} | 
          <span class="font-medium">Generated By:</span> {{ viewing.generatedBy }}
        </div>
        <div class="bg-gray-50 rounded-lg p-4">
          <h4 class="font-medium text-gray-900 mb-2">Preview:</h4>
          <pre class="text-sm text-gray-700 whitespace-pre-wrap">{{ viewing.preview }}</pre>
        </div>
        <div class="mt-6 flex justify-end space-x-3">
          <button 
            @click="viewing = null" 
            class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200"
          >
            Close
          </button>
          <button 
            @click="downloadReport(viewing)" 
            class="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700"
          >
            Download
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ReportsTab',
  props: {
    reports: { type: Array, required: true },
    patients: { type: Array, default: () => [] }
  },
  data() {
    return {
      filterType: '',
      from: '',
      to: '',
      viewing: null
    }
  },
  computed: {
    types() { return [...new Set(this.reports.map(r => r.type))] },
    filteredReports() {
      const fromTs = this.from ? new Date(this.from).getTime() : 0
      const toTs = this.to ? new Date(this.to).getTime() : Infinity
      return this.reports.filter(r => {
        if (this.filterType && r.type !== this.filterType) return false
        const d = new Date(r.date).getTime()
        return d >= fromTs && d <= toTs
      })
    }
  },
  methods: {
    generateReport() {
      // Generate a new report
      const id = 'R-' + Math.floor(Math.random()*9000 + 1000)
      const reportTypes = ['Summary', 'Export', 'Occupancy', 'Discharge', 'Financial']
      const randomType = reportTypes[Math.floor(Math.random() * reportTypes.length)]
      
      const newReport = { 
        id, 
        title: `${randomType} Report ${id}`, 
        type: randomType, 
        date: new Date().toISOString().slice(0,10), 
        generatedBy: 'Hospital Administrator',
        status: 'Ready'
      }
      this.reports.push(newReport)
      
      // Show success notification
      this.$emit('report-generated', newReport)
      console.log('Generated report:', newReport.title)
    },
    getStatusClass(status) {
      const classes = {
        'Ready': 'bg-green-100 text-green-800',
        'Processing': 'bg-yellow-100 text-yellow-800',
        'Failed': 'bg-red-100 text-red-800'
      }
      return classes[status] || 'bg-gray-100 text-gray-800'
    },
    downloadReport(r) {
      // demo: generate CSV from patients
      const rows = this.patients.length ? this.patients : [{ id:'n/a', name:'no-data' }]
      const keys = Object.keys(rows[0])
      const csv = [keys.join(',')].concat(rows.map(row => keys.map(k => `"${String(row[k] ?? '')}"`).join(','))).join('\n')
      const blob = new Blob([csv], { type: 'text/csv' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a'); a.href = url; a.download = `${r.title}.csv`; a.click(); a.remove()
      URL.revokeObjectURL(url)
    },
    viewReport(r) {
      this.viewing = Object.assign({}, r, { preview: 'Demo preview for ' + r.title + '\n\nThis is sample content for the report.' })
    }
  }
}
</script>

<style scoped>
pre { white-space: pre-wrap; }
</style>

